parameters:

    fridge.subscription.manager.base_manager.class:                     Fridge\SubscriptionBundle\Manager\BaseManager
    fridge.subscription.manager.subscription_manager.class:             Fridge\SubscriptionBundle\Manager\SubscriptionManager
    fridge.subscription.manager.card_manager.class:                     Fridge\SubscriptionBundle\Manager\CardManager
    fridge.subscription.manager.stripe_profile_manager.class:           Fridge\SubscriptionBundle\Manager\StripeProfileManager

    fridge.subscription.entity.subscription.class:                      Fridge\SubscriptionBundle\Entity\Subscription
    fridge.subscription.entity.stripe_profile.class:                    Fridge\SubscriptionBundle\Entity\StripeProfile
    fridge.subscription.entity.card.class:                              Fridge\SubscriptionBundle\Entity\Card
    fridge.subscription.entity.stripe_profile.class:                    Fridge\SubscriptionBundle\Entity\StripeProfile

    fridge.subscription.proxy.abstract_stripe_proxy.class:              Fridge\SubscriptionBundle\Proxy\AbstractStripeProxy
    fridge.subscription.proxy.stripe_customer.class:                    Fridge\SubscriptionBundle\Proxy\StripeCustomer
    fridge.subscription.proxy.stripe_plan.class:                        Fridge\SubscriptionBundle\Proxy\StripePlan
    fridge.subscription.proxy.stripe_event.class:                       Fridge\SubscriptionBundle\Proxy\StripeEvent
    fridge.subscription.proxy.stripe_card.class:                        Fridge\SubscriptionBundle\Proxy\StripeCard

    fridge.subscription.listener.abstract_entity_event_listener.class:  Fridge\SubscriptionBundle\EventListener\AbstractEntityEventListener
    fridge.subscription.listener.stripe_profile_listener.class:         Fridge\SubscriptionBundle\EventListener\StripeProfileListener
    fridge.subscription.listener.subscription_listener.class:           Fridge\SubscriptionBundle\EventListener\SubscriptionListener
    fridge.subscription.listener.card_listener.class:                   Fridge\SubscriptionBundle\EventListener\CardListener
    fridge.subscription.listener.webhook_lister.class:                  Fridge\SubscriptionBundle\EventListener\WebhookListener

    fridge.subscription.factory.operation_factory.class:                Fridge\SubscriptionBundle\Factory\OperationFactory

    zfr.client.stripe_client.class:                                     ZfrStripe\Client\StripeClient

services:


    #Factory

    fridge.subscription.factory.operation_factory:
        class: %fridge.subscription.factory.operation_factory.class%
        arguments: [@fridge.subscription.proxy.stripe_customer, @fridge.subscription.proxy.stripe_plan, @fridge.subscription.proxy.stripe_card]

    #Proxies

    zfr.client.stripe_client:
        class: %zfr.client.stripe_client.class%
        arguments: ['%fridge_subscription.stripe_sk%']

    fridge.subscription.proxy.abstract_stripe_proxy:
        abstract: true
        class: %fridge.subscription.proxy.abstract_stripe_proxy.class%
        arguments: [@zfr.client.stripe_client]

    fridge.subscription.proxy.stripe_customer:
        class: %fridge.subscription.proxy.stripe_customer.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    fridge.subscription.proxy.stripe_plan:
        class: %fridge.subscription.proxy.stripe_plan.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    fridge.subscription.proxy.stripe_event:
        class: %fridge.subscription.proxy.stripe_event.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    fridge.subscription.proxy.stripe_card:
        class: %fridge.subscription.proxy.stripe_card.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    #Managers

    fridge.subscription.manager.base_manager:
        class: %fridge.subscription.manager.base_manager.class%
        abstract: true
        calls:
            - [ setDoctrine, [ @doctrine ] ]
            - [ setSecurityContext, [ @security.context ] ]

    fridge.subscription.manager.subscription_manager:
        class: %fridge.subscription.manager.subscription_manager.class%
        parent: fridge.subscription.manager.base_manager
        arguments: [%fridge.subscription.entity.subscription.class%]

    fridge.subscription.manager.card_manager:
        class: %fridge.subscription.manager.card_manager.class%
        parent: fridge.subscription.manager.base_manager
        arguments: [%fridge.subscription.entity.card.class%]

    fridge.subscription.manager.stripe_profile_manager:
        class: %fridge.subscription.manager.stripe_profile_manager.class%
        parent: fridge.subscription.manager.base_manager
        arguments: [%fridge.subscription.entity.stripe_profile.class%]

    #Listeners

    fridge.subscription.listener.webhook_lister:
        class: %fridge.subscription.listener.webhook_lister.class%
        arguments: [@logger, @fridge.subscription.proxy.stripe_event, @fridge.subscription.factory.operation_factory, @fridge.subscription.manager.stripe_profile_manager]
        tags:
            - { name: kernel.event_subscriber }

    fridge.subscription.listener.abstract_entity_event_listener:
        class: %fridge.subscription.listener.abstract_entity_event_listener.class%
        abstract: true
        arguments: [@fridge.subscription.factory.operation_factory]

    fridge.subscription.listener.stripe_profile_listener:
        class: %fridge.subscription.listener.stripe_profile_listener.class%
        parent: fridge.subscription.listener.abstract_entity_event_listener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setEntityClass, [ '%fridge.subscription.entity.stripe_profile.class%' ] ]

    fridge.subscription.listener.subscription_listener:
        class: %fridge.subscription.listener.subscription_listener.class%
        parent: fridge.subscription.listener.abstract_entity_event_listener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setEntityClass, [ '%fridge.subscription.entity.subscription.class%' ] ]

    fridge.subscription.listener.card_listener:
        class: %fridge.subscription.listener.card_listener.class%
        parent: fridge.subscription.listener.abstract_entity_event_listener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setEntityClass, [ '%fridge.subscription.entity.card.class%' ] ]