parameters:

    fridge.subscription.manager.base_manager.class:               Fridge\SubscriptionBundle\Manager\BaseManager
    fridge.subscription.manager.subscription_manager.class:       Fridge\SubscriptionBundle\Manager\SubscriptionManager

    fridge.subscription.entity.subscription.class:                Fridge\SubscriptionBundle\Entity\Subscription
    fridge.subscription.entity.stripe_profile.class:              Fridge\SubscriptionBundle\Entity\StripeProfile

    fridge.subscription.proxy.abstract_stripe_proxy.class:        Fridge\SubscriptionBundle\Proxy\AbstractStripeProxy
    fridge.subscription.proxy.stripe_customer.class:              Fridge\SubscriptionBundle\Proxy\StripeCustomer
    fridge.subscription.proxy.stripe_plan.class:                  Fridge\SubscriptionBundle\Proxy\StripePlan

    fridge.subscription.listener.stripe_profile_listener.class:   Fridge\SubscriptionBundle\EventListener\StripeProfileListener
    fridge.subscription.listener.subscription_listener.class:     Fridge\SubscriptionBundle\EventListener\SubscriptionListener

services:

    fridge.subscription.manager.base_manager:
        class: %fridge.subscription.manager.base_manager.class%
        abstract: true
        calls:
            - [ setDoctrine, [ @doctrine ] ]
            - [ setSecurityContext, [ @security.context ] ]

    fridge.subscription.proxy.abstract_stripe_proxy:
        class: %fridge.subscription.proxy.abstract_stripe_proxy.class%
        abstract: true
        calls:
            - [ setApiKey, [ '%fridge_subscription.stripe_sk%' ] ]

    fridge.subscription.proxy.stripe_customer:
        class: %fridge.subscription.proxy.stripe_customer.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    fridge.subscription.proxy.stripe_plan:
        class: %fridge.subscription.proxy.stripe_plan.class%
        parent: fridge.subscription.proxy.abstract_stripe_proxy

    fridge.subscription.manager.subscription_manager:
        class: %fridge.subscription.manager.subscription_manager.class%
        parent: fridge.subscription.manager.base_manager
        arguments: [%fridge.subscription.entity.subscription.class%]

    fridge.subscription.listener.stripe_profile_listener:
        class: %fridge.subscription.listener.stripe_profile_listener.class%
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
        arguments: [@fridge.subscription.proxy.stripe_customer, '%fridge.subscription.entity.stripe_profile.class%' ]

    fridge.subscription.listener.subscription_listener:
        class: %fridge.subscription.listener.subscription_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments: [@fridge.subscription.proxy.stripe_plan, '%fridge.subscription.entity.subscription.class%']
